script: ./deploy.sh
env:
  global:
  - GH_REF: github.com/yefim/yefim.git
  - secure: "s0E3p6+IdUMc3VEMxmLb3gwfp6ZrsTZzk8Q+7de5/1IpMYuvKx0btdkwusATi/dBLxVgXc62+4aFH6qlwDJjdmW0zFPDVtIGP3PU9lPrMjLB6SdRgSjzQ+MqEGixy+FL8Xl4znb1qiH2xArTUaoXIP9OeUNU1c+ImtDHTYAV/XtUp2FN3xrXh/WxnMcbPxp4DloZ5Fe/vrrpzMD+4hYxcBmWZ3/H925wCaMt3x3x2+EQKraNcjlilFkzuMjtRB0/a8i6NP57nJyVxUfb/iw7UFGvEV/KA7XMx3VaQVJso8EeerqhRTfLAwmonf19A6jlvWmtTj8Y4W0bVVFqqQZkrtDN8NFrmXVV2o5tVeLKzrNOKOHEo9wSb4zPYqeieOAVds7iiRDjOcc9avJhGVpcLlTihEBvn+spCvPBaQkyNk8rYMJYpEDZIr/9p5SG0i4sFVjedOIW4rI7GzqDiZ68/A3EfFyVGvXQaL1EkN3quU4FCUfNfo4m27ceQlKeXgAjUUHj/cOjv2EZ19pUwUB0+3LQdpt0tZbBDXEpNKUzP0D6VhWLILr1bVrfOht4EefsMomcauMIRC4jsSBihIV5f5KpxOTH43V9Gz6FPiZCGsUzbR58+BIlLdhVihqh1l2X/2pce203aBXeRRC7KK/E2X2hr05qie9by1stSRUn5IE="
language: node_js
node_js:
- "6"
sudo: false
cache:
  directories:
  - node_modules
